# Wrangler configuration for Cloudflare Pages
name = "honeyhive-app"
compatibility_date = "2023-10-30"

# Configure Functions for specific routes
[[routes]]
pattern = "/"
script = ""

[[routes]]
pattern = "/api/*"
script = "dist/functions/api/[wildcard]"

# Bind environment variables to the application
[vars]
  # These will be overridden by the Cloudflare dashboard environment variables
  NODE_ENV = "production"

# Set compatibility flags for up-to-date features
[build]
  command = "npm run build"
  output_dir = "dist" 