name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # or main, depending on your default branch

permissions:
  contents: write

env:
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
  VITE_TURNSTILE_SITE_KEY: ${{ secrets.VITE_TURNSTILE_SITE_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Debug - List environment variables (redacted values)
        run: |
          echo "Environment variables available (showing if set):"
          echo "VITE_SUPABASE_URL is set: ${{ env.VITE_SUPABASE_URL != '' }}"
          echo "VITE_SUPABASE_ANON_KEY is set: ${{ env.VITE_SUPABASE_ANON_KEY != '' }}"
          echo "VITE_TURNSTILE_SITE_KEY is set: ${{ env.VITE_TURNSTILE_SITE_KEY != '' }}"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Create init-env.js with actual environment values
      - name: Create init-env.js with environment variables
        run: |
          cat > ./dist/init-env.js << EOF
          // This script is generated at build time by GitHub Actions
          // It initializes environment variables before the main app loads

          // Define global Supabase variables
          window.VITE_SUPABASE_URL = "${{ env.VITE_SUPABASE_URL }}";
          window.VITE_SUPABASE_ANON_KEY = "${{ env.VITE_SUPABASE_ANON_KEY }}";
          window.env = {
            CLOUDFLARE_TURNSTILE_SITE_KEY: "${{ env.VITE_TURNSTILE_SITE_KEY }}"
          };

          console.log("Environment initialization complete");
          EOF

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist 